import React from 'react'
import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import { useTheme } from '@/context/ThemeProvider'

interface CashFlowAreaChartProps {
  data: {
    item: string
    [key: string]: string | number | null
  }[]
}

export default function CashFlowAreaChart({ data }: CashFlowAreaChartProps) {
  const { theme } = useTheme()
  const isDark = theme === 'dark'

  // Extract years
  const years = Object.keys(data[0] || {})
    .filter((key) => key !== 'item')
    .sort()

  // Helper to get value for a given item and year
  const findValue = (itemName: string, year: string) => {
    const item = data.find((d) => d.item === itemName)
    return item ? (item[year] as number) : 0
  }

  // Prepare series data
  const operating = years.map((year) =>
    findValue('Cash generated by operating activities', year),
  )
  const investing = years.map((year) =>
    findValue('Cash generated by/(used in) investing activities', year),
  )
  const financing = years.map((year) =>
    findValue('Cash used in financing activities', year),
  )

  const option: EChartsOption = {
    backgroundColor: 'transparent',
    tooltip: {
      trigger: 'axis',
      axisPointer: { type: 'cross', label: { backgroundColor: '#6a7985' } },
      backgroundColor: isDark ? 'rgba(0,0,0,0.8)' : 'rgba(255,255,255,0.9)',
      borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
      borderWidth: 1,
      padding: [8, 12],
      textStyle: {
        color: isDark ? '#fff' : '#000',
        fontFamily: 'Inter, sans-serif',
      },
    },
    legend: {
      data: ['Operating', 'Investing', 'Financing'],
      textStyle: { color: isDark ? '#fff' : '#000' },
    },
    xAxis: [
      {
        type: 'category',
        data: years,
        axisLabel: { color: isDark ? '#fff' : '#000' },
      },
    ],
    yAxis: [
      {
        type: 'value',
        axisLabel: {
          formatter: (value: number) => `$${(value / 1000).toFixed(0)}B`,
          color: isDark ? '#fff' : '#000',
        },
        splitLine: {
          lineStyle: {
            color: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
          },
        },
      },
    ],
    series: [
      {
        name: 'Operating',
        type: 'line',
        stack: 'cashflow',
        areaStyle: {},
        emphasis: { focus: 'series' },
        data: operating,
        itemStyle: { color: '#22c55e' },
        lineStyle: { color: '#22c55e' },
      },
      {
        name: 'Investing',
        type: 'line',
        stack: 'cashflow',
        areaStyle: {},
        emphasis: { focus: 'series' },
        data: investing,
        itemStyle: { color: '#3b82f6' },
        lineStyle: { color: '#3b82f6' },
      },
      {
        name: 'Financing',
        type: 'line',
        stack: 'cashflow',
        areaStyle: {},
        emphasis: { focus: 'series' },
        data: financing,
        itemStyle: { color: '#f59e42' },
        lineStyle: { color: '#f59e42' },
      },
    ],
    grid: { left: 40, right: 40, top: 60, bottom: 40 },
  }

  return (
    <ReactECharts
      option={option}
      style={{ height: '400px', width: '100%' }}
      theme={isDark ? 'dark' : undefined}
    />
  )
}
