import React from 'react'
import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import { useTheme } from '@/context/ThemeProvider'

interface CashFlowCombinedChartProps {
  data: {
    item: string
    [key: string]: string | number | null
  }[]
}

export default function CashFlowCombinedChart({
  data,
}: CashFlowCombinedChartProps) {
  const { theme } = useTheme()
  const isDark = theme === 'dark'

  // Extract years
  const years = Object.keys(data[0] || {})
    .filter((key) => key !== 'item')
    .sort()

  // Helper to get value for a given item and year
  const findValue = (itemName: string, year: string) => {
    const item = data.find((d) => d.item === itemName)
    return item ? (item[year] as number) : 0
  }

  // Prepare series data
  const operating = years.map((year) =>
    findValue('Cash generated by operating activities', year),
  )
  const investing = years.map((year) =>
    findValue('Cash generated by/(used in) investing activities', year),
  )
  const financing = years.map((year) =>
    findValue('Cash used in financing activities', year),
  )
  const netChange = years.map((year) =>
    findValue(
      'Increase/(Decrease) in cash, cash equivalents, and restricted cash and cash equivalents',
      year,
    ),
  )

  const option: EChartsOption = {
    backgroundColor: 'transparent',
    tooltip: {
      trigger: 'axis',
      axisPointer: { type: 'shadow' },
      backgroundColor: isDark ? 'rgba(0,0,0,0.8)' : 'rgba(255,255,255,0.9)',
      borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
      borderWidth: 1,
      padding: [8, 12],
      textStyle: {
        color: isDark ? '#fff' : '#000',
        fontFamily: 'Inter, sans-serif',
      },
    },
    legend: {
      data: ['Operating', 'Investing', 'Financing', 'Net Change'],
      textStyle: { color: isDark ? '#fff' : '#000' },
    },
    xAxis: [
      {
        type: 'category',
        data: years,
        axisLabel: { color: isDark ? '#fff' : '#000' },
      },
    ],
    yAxis: [
      {
        type: 'value',
        axisLabel: {
          formatter: (value: number) => `$${(value / 1000).toFixed(0)}B`,
          color: isDark ? '#fff' : '#000',
        },
        splitLine: {
          lineStyle: {
            color: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
          },
        },
      },
    ],
    series: [
      {
        name: 'Operating',
        type: 'bar',
        stack: 'cashflow',
        data: operating,
        itemStyle: { color: '#22c55e' },
      },
      {
        name: 'Investing',
        type: 'bar',
        stack: 'cashflow',
        data: investing,
        itemStyle: { color: '#3b82f6' },
      },
      {
        name: 'Financing',
        type: 'bar',
        stack: 'cashflow',
        data: financing,
        itemStyle: { color: '#f59e42' },
      },
      {
        name: 'Net Change',
        type: 'line',
        data: netChange,
        symbol: 'circle',
        symbolSize: 12,
        lineStyle: { width: 4, color: '#ef4444' },
        itemStyle: { color: '#ef4444' },
        z: 10,
      },
    ],
    grid: { left: 40, right: 40, top: 60, bottom: 40 },
  }

  return (
    <ReactECharts
      option={option}
      style={{ height: '400px', width: '100%' }}
      theme={isDark ? 'dark' : undefined}
    />
  )
}
